Repository intuit/accessibility-snippets, pull requests merged in 2021-07, with the labels that each got.

#23 Add ARIA:document role
  README.md
  snippets/react-snippets.code-snippets
Labels: minor

#25 Fix build
  package.json
Labels: patch

#24 Just trying to get all contributors working
  README.md
Labels: documentation, patch
