Repository intuit/accessibility-snippets, pull requests merged in 2021-10, with the labels that each got.

#34 Add Aria: Loading Spinner
  README.md
  snippets/react-snippets.code-snippets
Labels: minor

#35 Added ARIA: Searchbox role
  README.md
  snippets/react-snippets.code-snippets
Labels: minor

#43 OSD Contribution : Add ARIA:Cell Role
  README.md
  snippets/react-snippets.code-snippets
Labels: minor

#48 Add Aria: Image Role
  README.md
  snippets/react-snippets.code-snippets
Labels: minor

#49 Added CSS snippet: prefers-color-scheme: dark
  README.md
  snippets/css-snippets.code-snippets
Labels: minor

#45 Adding contrast to csss accessibility snippets
  README.md
  snippets/css-snippets.code-snippets
Labels: minor

#42 fixed Add Aria: separator#31
  README.md
  snippets/react-snippets.code-snippets
Labels: minor

#55 Add ARIA: Light color scheme css snippet
  README.md
  snippets/css-snippets.code-snippets
Labels: minor

#44 Add tests
  README.md
  __tests__/index.js
  package.json
  snippets/css-snippets.json
  snippets/react-snippets.json
  yarn.lock
Labels: patch

#51 Making README.md more readable
  README.md
Labels: patch

#64 Update README.md for MeterAria description
  README.md
Labels: documentation

#62 Added MeterAria
  snippets/react-snippets.code-snippets
Labels: minor
